print("#1")
fruits = ["apple", "banana", "cherry"]
print(fruits[0])  
print(fruits[-1])
print(fruits[:])
print("..............................")
print("#2")
fruits.append("date")
fruits.extend(["elderberry", "fig"])
print(fruits[:])
fruits.insert(2, "grape")
print(fruits[:])
print("..............................")
print("#3")
fruits.remove("banana")
print(fruits[:])
fruits.pop(-1)
print(fruits[:])
del fruits[1]
print(fruits[:])
fruits.clear()
print(fruits[:])
print("..............................")
print("#4")
numbers = [1, 2, 3, 4]
print(numbers[:])
numbers[1] = 20
print(numbers[:])
numbers[2:3] = [30, 40]
print(numbers[:])
numbers = [1, 2, 3, 4]*2
print(numbers[:])
print("..............................")
print("#5")
numbers = [4,7,2,7,5]
print(numbers[:])
numbers.count(7)
print(numbers.count(7))
numbers.sort()
print(numbers[:])
numbers.reverse()
print(numbers[:])
print(len(numbers))
print(max(numbers))
print(sum(numbers))
print("..............................")
print("#6")
date = [3,5,2,5,7,5,1]
print(4 in date)
print(date.count(5))
dates = date[1:5]
print(dates)
dates.reverse()
print(list(reversed(dates)))
print(dates * 2)
dates.pop(-1)
print(dates[:])
print("..............................")